# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.PositiveIntegerField(verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.PositiveIntegerField(verbose_name='id')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonsheep.Project', verbose_name='project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField(verbose_name='id')),
                ('verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('clean', models.BooleanField(default=False, verbose_name='is clean')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moonsheep.Task', verbose_name='task')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonsheep.Report', verbose_name='report')),
            ],
        ),
    ]
