# Generated by Django 2.2.5 on 2019-11-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonsheep', '0002_auto_20191105_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
