# Generated by Django 2.2.5 on 2019-11-05 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonsheep', '0003_auto_20190821_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='own_progress',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='total_progress',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
