# Generated by Django 2.2.5 on 2019-11-14 16:40

import django.core.serializers.json
from django.db import migrations
import moonsheep.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('moonsheep', '0004_auto_20191106_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='data2',
            field=moonsheep.json_field.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='params2',
            field=moonsheep.json_field.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='data',
            field=moonsheep.json_field.JSONTextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='params',
            field=moonsheep.json_field.JSONTextField(blank=True),
        ),
    ]
