# Generated by Django 2.2.5 on 2019-11-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonsheep', '0006_auto_20191114_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='params',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='data2',
            new_name='data'
        ),
        migrations.RenameField(
            model_name='task',
            old_name='params2',
            new_name='params',
        ),
    ]
