# Generated by Django 2.2.5 on 2019-11-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonsheep', '0008_auto_20191114_1653'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='unique_task_user',
        ),
        migrations.AddField(
            model_name='entry',
            name='closed_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('task', 'user', 'closed_manually'), name='unique_task_user'),
        ),
    ]
